<#
.SYNOPSIS
    WinPurge Compilation Script
    
.DESCRIPTION
    Concatenates all modular .ps1 files into a single distributable script.
    Includes:
    - Core modules (logging, elevation, audit, dry-run)
    - Tweak modules (telemetry, services, privacy, etc.)
    - AI protection modules
    - Install/ISO utilities
    - Plugin system
    - Preset manager
    
    Output: WinPurge-Standalone.ps1 (single file, no dependencies)
#>

param(
    [string]$OutputPath = "WinPurge-Standalone.ps1",
    [switch]$Minify,
    [switch]$IncludePresets = $true
)

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$version = "2.0"

Write-Host "[WinPurge Compiler] Building standalone executable..." -ForegroundColor Cyan
Write-Host "Timestamp: $timestamp" -ForegroundColor Gray
Write-Host "Version: $version" -ForegroundColor Gray

$moduleOrder = @(
    # Core modules (must load first)
    'src/Core/Logging.ps1',
    'src/Core/Elevation.ps1',
    'src/Core/DryRun.ps1',
    'src/Core/AuditLog.ps1',
    'src/Core/RestorePoint.ps1',
    'src/Core/VersionCheck.ps1',
    'src/Core/Benchmark.ps1',
    
    # Tweak modules
    'src/Tweaks/Telemetry.ps1',
    'src/Tweaks/Bloatware.ps1',
    'src/Tweaks/Services.ps1',
    'src/Tweaks/Privacy.ps1',
    'src/Tweaks/Registry.ps1',
    'src/Tweaks/Network.ps1',
    'src/Tweaks/FileExplorer.ps1',
    'src/Tweaks/Taskbar.ps1',
    'src/Tweaks/StartMenu.ps1',
    'src/Tweaks/WindowsUpdate.ps1',
    
    # AI Protection modules
    'src/AI/AIProtection.ps1',
    'src/AI/AIReinstallBlock.ps1',
    'src/AI/PostUpdateCleanup.ps1',
    'src/AI/ClassicAppReplace.ps1',
    
    # Utility modules
    'src/Install/WingetHelper.ps1',
    'src/Iso/DisMHelper.ps1',
    'src/Iso/UnattendGenerator.ps1',
    'src/Plugins/PluginLoader.ps1',
    'src/Presets/PresetManager.ps1'
)

$compiledContent = @"
#Requires -Version 7.0
<#
.SYNOPSIS
    WinPurge v$version - Advanced Windows Debloater/Tweaker (STANDALONE)
    
.DESCRIPTION
    Compiled standalone version. All modules included.
    All dependencies bundled into single distributable script.
    
.NOTES
    Generated: $timestamp
    Compilation: Automatic
    License: MIT
    Repository: https://github.com/ScriptSage196/WinPurge
    
    For updates and latest version, visit the GitHub repository.
#>

# ============================================================================
# COMPILED: WinPurge v$version Standalone
# ============================================================================
# This file contains all modules compiled together.
# Do not edit - this is auto-generated by Compile.ps1
# ============================================================================

"@

$moduleCount = 0

foreach ($modulePath in $moduleOrder) {
    if (Test-Path $modulePath) {
        $moduleContent = Get-Content $modulePath -Raw
        
        # Remove comment headers and #Requires
        $moduleContent = $moduleContent -replace '^#Requires.*?\n', ''
        $moduleContent = $moduleContent -replace '^<#[\s\S]*?#>\s*\n', ''
        
        $moduleName = Split-Path $modulePath -Leaf
        $compiledContent += "`n# ============================================================================`n"
        $compiledContent += "# MODULE: $moduleName`n"
        $compiledContent += "# ============================================================================`n"
        $compiledContent += $moduleContent
        $compiledContent += "`n`n"
        
        $moduleCount++
        Write-Host "✓ Included: $moduleName" -ForegroundColor Green
    }
    else {
        Write-Host "✗ Missing: $modulePath" -ForegroundColor Yellow
    }
}

# Add main entry point
$compiledContent += @"

# ============================================================================
# ENTRY POINT
# ============================================================================

Write-Host "WinPurge v$version Standalone Loaded" -ForegroundColor Cyan
Write-Host "All modules compiled and ready to use" -ForegroundColor Green
Write-Host "Run 'Get-AvailablePresets' to see available presets" -ForegroundColor Cyan

"@

# Optionally minify
if ($Minify) {
    Write-Host "Minifying code..." -ForegroundColor Yellow
    $compiledContent = $compiledContent -replace '\s*#.*?\n', "`n"
    $compiledContent = $compiledContent -replace '\n\s*\n', "`n"
}

# Write output
try {
    $compiledContent | Out-File -FilePath $OutputPath -Encoding UTF8 -Force
    $fileSize = (Get-Item $OutputPath).Length / 1KB
    
    Write-Host "`n" -ForegroundColor Cyan
    Write-Host "════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "✓ Compilation Successful" -ForegroundColor Green
    Write-Host "════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "Output: $OutputPath" -ForegroundColor White
    Write-Host "Modules: $moduleCount" -ForegroundColor White
    Write-Host "Size: $([math]::Round($fileSize, 2)) KB" -ForegroundColor White
    Write-Host "Version: $version" -ForegroundColor White
    Write-Host "════════════════════════════════════════════════════" -ForegroundColor Cyan
    
    Write-Host "`nUsage:
  .\$OutputPath -GUI
  .\$OutputPath -Preset Gaming -DryRun
  .\$OutputPath -Headless -Preset Minimal" -ForegroundColor Yellow
}
catch {
    Write-Host "✗ Compilation failed: $_" -ForegroundColor Red
    exit 1
}
